### ISSUE TITLE
The theme issue

### ISSUE THREAD

**Issue by SuzukiHonoka** [Lennoard/SysctlGUI#1]
The default theme of app is too dark that I can't even see clearly one word,
Please adjust the light of theme or use the high light theme,
THANKS!

**Comment by Lennoard** [comment]
The theme has sufficient (and even recommended) contrast ratio. What I can do is provide a light theme variant.

**Comment by Lennoard** [comment]
Bug confirmed in non-sytem-wide night mode

**Comment by Lennoard** [comment]
Addressed in 6fc0109
