### ISSUE TITLE
Todays release (1.0.7) broken?

### ISSUE THREAD

**Issue by IzzySoft** [Lennoard/SysctlGUI#16]
Just wondering:

* attached APK is named `sysctlgui-v1.0.8.apk` though tag suggests v1.0.7
* `apksigner` complains the APK "does not verify" (did you forget to sign? Remember that v2 was only introduced with Android 7, so up to Android 6 v1 (JAR) signature is required).

```
$ apksigner verify --verbose sysctlgui-v1.0.8.apk 
DOES NOT VERIFY
ERROR: No JAR signatures
$ apksigner version
0.9
```

Can you please verify and replace the APK? Thanks!

**Comment by Lennoard** [comment]
I definitely messed up. One signature is missing. And the version code is wrong that's why the release apk has 1.0.8 automatically added to it. I'll fix it as soon as I get back to my computer.

**Comment by IzzySoft** [comment]
Great, thanks a lot – looking forward to that!

PS: Hope [you like this](https://apt.izzysoft.de/fdroid/?author=Lennoard+Silva) (DD GUI will show up in that list tomorrow, after the next sync). If you want to link there from your resp. Readmes, I can provide you with a [fitting badge](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) :smiley: Updates are pulled within 24h of your creating a new tag and attaching the APK to it, which is how this issue was brought to my attention (my updater sent me a complaint :rofl:)

**Comment by Lennoard** [comment]
APK replaced. Also check f1205dd for the version name and ae44101 for the badge

**Comment by IzzySoft** [comment]
Cool, thanks! Even placed the link to my repo first :heart_eyes: In this case I simply had to trigger a manual run: confirmed, indexed, syncing now – then wait for Brainstorm to announce it on IRC and Reddit :tada:

As it's definitely solved, I'm closing this issue. Oh, and [DD GUI is available now](https://apt.izzysoft.de/fdroid/index/apk/com.androidvip.ddgui) as well, with the sync just finished :smiley: And there comes Brainstorm, announcement is out, yay! :raised_hands:
