### ISSUE TITLE
Backup parameter

### ISSUE THREAD

**Issue by Mahantor** [Lennoard/SysctlGUI#24]
How backup kernel parametr and restore in another kernel???

**Comment by Lennoard** [comment]
You don't actually restore, you reapply your settings.

**Comment by Mahantor** [comment]
It is possible to add the ability of backup and restore in the next eternity

**Comment by Mahantor** [comment]
> You don't actually restore, you reapply your settings.

It is possible to add the ability of backup and restore in the next eternity

**Comment by Lennoard** [comment]
The app already has an export/import functionality in the settings page.
If you want something different please feel free to write a detailed specification.

**Comment by Mahantor** [comment]
> The app already has an export/import functionality in the settings page. If you want something different please feel free to write a detailed specification.

Yes, but only changed parameters can be backed up
I exported my default kernel parameters without any changes but the file was empty

**Comment by Lennoard** [comment]
Closing this with [release v1.1.0](https://github.com/Lennoard/SysctlGUI/releases/tag/1.1.0) via #26
