### ISSUE TITLE
In Browse variables, nothing appears under net

### ISSUE THREAD

**Issue by 2011** [Lennoard/SysctlGUI#35]
Great app, at least in theory. Unfortunately, when I change net.ipv6.conf.all.disable_ipv6 to 1, something keeps changing net.ipv6.conf.wlan0.disable_ipv6 back to 0 within a few seconds (while leaving all of the other disable_ipv6 variables at 1). If you know what causes that, let me know. :)

Anyway, I doubt that represents a problem with your program. I opened this issue because when I go into "Browse variables", I can go up and down the entire tree, except for the net subtree. When I select "net", I see "/proc/sys/net" at the top, but with absolutely none of the entries in that directory displayed. I expect to see these:

```
# ls -al /proc/sys/net/
total 0
dr-xr-xr-x    1 root     root             0 1972-05-20 11:27:02 +0000 .
dr-xr-xr-x    1 root     root             0 1972-05-20 11:26:59 +0000 ..
dr-xr-xr-x    1 root     root             0 1972-05-20 11:27:02 +0000 core
dr-xr-xr-x    1 root     root             0 1972-05-20 11:27:02 +0000 ipv4
dr-xr-xr-x    1 root     root             0 1972-05-20 11:27:02 +0000 ipv6
dr-xr-xr-x    1 root     root             0 2022-04-02 03:49:35 +0000 netfilter
-rw-r--r--    1 root     root             0 2022-04-02 03:49:35 +0000 nf_conntrack_max
dr-xr-xr-x    1 root     root             0 2022-04-02 03:49:35 +0000 sctp
dr-xr-xr-x    1 root     root             0 2022-04-02 03:49:35 +0000 unix
```

I can easily locate variables under net by searching for them after selecting "Show variables", but I have no idea why the app doesn't display them as part of the tree.

**Comment by Lennoard** [comment]
I've seen this behavior before.
I have to investigate why that's happening. Currently I have no idea since it's a "folder" just like any other.

**Comment by Mylinde** [comment]
In Android 13 the structure of /proc/sys/net is different, it has subfolders.
[net.txt](https://github.com/Lennoard/SysctlGUI/files/12138186/net.txt)
