### ISSUE TITLE
Doesn't work on reboot

### ISSUE THREAD

**Issue by s1nistr4** [Lennoard/SysctlGUI#56]
I have a fully rooted phone. When you set a kernel parameter and reboot it does not persist, even if you set it to in the settings.

**Comment by free-bots** [comment]
Hi @s1nistr4 
﻿Could you please tell me which Android version you are using and what specific parameters you would like to modify?
With lineage os 20 everything works as expected.

**Comment by Lennoard** [comment]
Possibly fixed with a combination of [b5dbba9] and [c54d037] in PR #65
