### ISSUE TITLE
Can you enable MASS_STORAGE?

### ISSUE THREAD

**Issue by erzurum2525** [Lennoard/SysctlGUI#67]
title
Thanks in advance

**Comment by Lennoard** [comment]
Any references? It's unclear what the app can do in relation to that.

**Comment by erzurum2525** [comment]
mass_storage is a setting that is in boot.img and when it is enabled you can plug your device to your PC and your PC will see it as a flashdrive. most devices have this enabled but I don't

**Comment by erzurum2525** [comment]
btw sorry for replying late

**Comment by free-bots** [comment]
@erzurum2525  there is an app in fdroid called "USB Mountr". Its no longer maintained and only accessible via the fdroid archive repos, maybe you can give it a shot.

https://github.com/donfanning/android_usb_msd
https://github.com/dratini0/phonestick
